services:
  backup-sync-s3:
    image: ${RCLONE_IMAGE}:${RCLONE_IMAGE_TAG}
    container_name: backup-sync-s3
    restart: unless-stopped
    entrypoint: /bin/sh -c "while true; do rclone sync /backups ${BACKUP_S3_BUCKET} --config /config/rclone.conf --s3-endpoint=${BACKUP_S3_ENDPOINT} --s3-access-key-id=${BACKUP_S3_ACCESS_KEY} --s3-secret-access-key=${BACKUP_S3_SECRET_KEY}; sleep ${BACKUP_SYNC_INTERVAL}; done"
    volumes:
      - ${BACKUP_PATH}:/backups:ro
    networks:
      - ${NETWORK_DATA}

networks:
  ${NETWORK_DATA}:
    external: true