services:
  postgres-backup:
    build:
      context: ./backup
      dockerfile: Dockerfile
    image: ${POSTGRES_BACKUP_IMAGE}:${POSTGRES_BACKUP_IMAGE_TAG}
    restart: unless-stopped
    user: postgres:postgres
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_SUPER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SUPER_PASSWORD}
      POSTGRES_CLUSTER: "TRUE"
      POSTGRES_DB: postgres
      POSTGRES_EXTRA_OPTS: ""
      SCHEDULE: ${BACKUP_SCHEDULE}
      BACKUP_ON_START: "TRUE"
      BACKUP_KEEP_DAYS: ${BACKUP_KEEP_DAYS}
      BACKUP_KEEP_WEEKS: ${BACKUP_KEEP_WEEKS}
      BACKUP_KEEP_MONTHS: ${BACKUP_KEEP_MONTHS}
      TZ: ${TZ}
      WEBHOOK_POST_BACKUP_URL: ${BACKUP_WEBHOOK_SUCCESS_URL}
      WEBHOOK_ERROR_URL: ${BACKUP_WEBHOOK_ERROR_URL}
    volumes:
      - ./backups:/backups
      - ./backup/hooks:/hooks
      - ./backup/rclone:/etc/rclone:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - data-net

networks:
  data-net:
    name: ${NETWORK_DATA}
    external: true