services:
  postgres:
    image: ${POSTGRES_IMAGE}:${POSTGRES_IMAGE_TAG}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_SUPER_USER}"]
      interval: ${HEALTHCHECK_INTERVAL}
      timeout: ${HEALTHCHECK_TIMEOUT}
      retries: ${HEALTHCHECK_RETRIES}
      start_period: ${HEALTHCHECK_START_PERIOD}
    deploy:
      resources:
        limits:
          memory: ${POSTGRES_MEMORY_LIMIT}
          cpus: ${POSTGRES_CPU_LIMIT}
        reservations:
          memory: ${POSTGRES_MEMORY_RESERVATION}
          cpus: ${POSTGRES_CPU_RESERVATION}
    environment:
      POSTGRES_USER: ${POSTGRES_SUPER_USER}
      POSTGRES_PASSWORD: ${POSTGRES_SUPER_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql
    networks:
      - data-net

networks:
  data-net:
    name: ${NETWORK_DATA}
    external: true