#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    -- Authentik database
    CREATE USER ${POSTGRES_AUTHENTIK_USER} WITH PASSWORD '${POSTGRES_AUTHENTIK_PASSWORD}';
    CREATE DATABASE ${POSTGRES_AUTHENTIK_DB} OWNER ${POSTGRES_AUTHENTIK_USER};
    
    -- Metabase database
    CREATE USER ${POSTGRES_METABASE_USER} WITH PASSWORD '${POSTGRES_METABASE_PASSWORD}';
    CREATE DATABASE ${POSTGRES_METABASE_DB} OWNER ${POSTGRES_METABASE_USER};
    
    -- Uptime Kuma database
    CREATE USER ${POSTGRES_UPTIME_KUMA_USER} WITH PASSWORD '${POSTGRES_UPTIME_KUMA_PASSWORD}';
    CREATE DATABASE ${POSTGRES_UPTIME_KUMA_DB} OWNER ${POSTGRES_UPTIME_KUMA_USER};
    
    -- tldraw database
    CREATE USER ${POSTGRES_DRAW_USER} WITH PASSWORD '${POSTGRES_DRAW_PASSWORD}';
    CREATE DATABASE ${POSTGRES_DRAW_DB} OWNER ${POSTGRES_DRAW_USER};
EOSQL